build:
  version: v3

cards:
  message: "Welcome to EazyBank Cards related Prod APIs "
  contactDetails:
    name: "John Doe - Prod Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345


spring:
  config:
    activate:
      on-profile: "prod"